/** Single source for names, copy, event details, links, and media paths. */
export const weddingConfig = Object.freeze({
  siteUrl: 'https://mohamad-adib-tawil.github.io/wedding-temp-2/',
  groom: { ar: 'محمد أديب طويل', displayAr: 'محمد', en: 'Mohamad Adib Tawil' },
  bride: { ar: 'رزان بطايحي', displayAr: 'رزان', en: 'Razan Bataihi' },
  weddingDate: '', // YYYY-MM-DD
  startTime: '', // HH:MM, local venue time
  endTime: '',
  timeZone: '', // IANA identifier, for example Asia/Damascus
  venue: '',
  address: '',
  mapsUrl: '',
  program: [], // [{ time: '19:00', title: '...' }]
  guestNotes: [],
  rsvp: {
    whatsappNumber: '', // International digits, without +
    contactName: '',
    deadline: '',
  },
  audioPath: 'assets/audio/nocturne-original.wav',
  socialPreviewPath: 'new_assets/social-preview-facing.jpg',
  copy: {
    pageTitle: 'دعوة زفاف محمد أديب طويل ورزان بطايحي',
    pageDescription: 'دعوة زفاف محمد أديب طويل ورزان بطايحي. يسعدنا أن تشاركونا فرحتنا.',
    occasion: 'دعوة زفاف',
    doorHint: 'المسوا الباب لتُفتح الحكاية',
    open: 'افتحوا الدعوة',
    skip: 'تخطّي المقدمة',
    mute: 'كتم الموسيقى',
    unmute: 'تشغيل الموسيقى',
    musicUnavailable: 'تعذّر تشغيل الموسيقى',
    continue: 'تابعوا الدعوة',
    heroKicker: 'على وعدٍ بليلةٍ لا تُنسى',
    heroLine: 'حين يلتقي قلبان، تكتمل الحكاية بحضوركم',
    scroll: 'اكتشفوا الدعوة',
    bismillah: 'بسم الله الرحمن الرحيم',
    invitationTitle: 'إلى من نحب',
    invitationMessage: 'بكل الحب، ندعوكم لتشاركونا فرحة زفافنا. وجودكم معنا يجعل هذه الليلة أجمل.',
    countdownTitle: 'حتى نلتقي',
    countdownComplete: 'حلّت ليلتنا، أهلًا بكم',
    days: 'يوم',
    hours: 'ساعة',
    minutes: 'دقيقة',
    seconds: 'ثانية',
    programTitle: 'برنامج الحفل',
    venueTitle: 'مكان الحفل',
    map: 'افتحوا الموقع على الخريطة',
    notesTitle: 'تنويهات',
    calendarTitle: 'أضيفوا الموعد إلى تقويمكم',
    calendarGoogle: 'تقويم Google',
    calendarIcs: 'تحميل ملف التقويم',
    rsvpTitle: 'تأكيد الحضور',
    rsvpDescription: 'يسعدنا تأكيد حضوركم عبر واتساب',
    rsvpDeadline: 'يرجى تأكيد الحضور قبل',
    rsvpButton: 'التأكيد عبر واتساب',
    rsvpMessage: 'مرحبًا، أود تأكيد حضوري حفل زفاف محمد أديب طويل ورزان بطايحي.',
    closing: 'بحضوركم تضيء ليلتنا',
    share: 'مشاركة الدعوة',
    copyLink: 'نسخ الرابط',
    copied: 'نُسخ رابط الدعوة',
    copyFailed: 'يمكنك نسخ رابط الدعوة من المتصفح',
    replay: 'إعادة عرض الدعوة',
  },
});
